package:
    name: libstatiskit_core
    version: "1.0.0"

source:
    path: ../..

build:
    number: 0
    script: 
        - scons cpp --prefix={{ PREFIX }} -j{{ CPU_COUNT }}          [unix]
        - scons cpp --prefix={{ LIBRARY_PREFIX }} -j{{ CPU_COUNT }}  [win]
    
about:
    home: http://statiskit-core.readthedocs.io/
    license: CeCILL

requirements:
    build:
        - libdev
        - libboost
        - eigen
    run:
        - libboost
        - eigen