package:
    name: libstatiskit_core
    version: "1.0.0"

source:
    path: ../..

build:
    number: 0
    
about:
    home: http://statiskit-core.readthedocs.io/
    license: CeCILL

requirements:
    build:
        - libdev
        - libboost
        - libstatiskit_linalg
    run:
        - libboost
        - libstatiskit_linalg