language: python

python: "2.7"

compiler: clang

before_install:
    - "cd .."
    - "git clone https://github.com/openalea/deploy.git"
    - "cd deploy"
    - "python setup.py install"
    - "cd .."
    - "git clone https://github.com/openalea/sconsx.git"
    - "cd sconsx"
    - "python setup.py install"
    - "cd .."
    - "cd StatisKit-Core"

install:
    - "scons"
