package:
    name: libstatiskit_core
    version: "1.0.0"

source:
    path: ../../..

build:
    number: 0
    
about:
    home: http://statiskit-core.readthedocs.io/
    license: Apache License 2.0

requirements:
    build:
        - libtoolchain
        - libboost-dev
        - libstatiskit_linalg
        - libstatiskit_stl
    run:
        - libstatiskit_linalg
        - libstatiskit_stl
