#include "_core.h"

class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator & (::std::unique_ptr< ::statiskit::ConditionalDistributionEstimation< ::statiskit::MultivariateConditionalDistribution >::Estimator, ::std::default_delete< ::statiskit::ConditionalDistributionEstimation< ::statiskit::MultivariateConditionalDistribution >::Estimator > >::*method_pointer_7302531c823b59459c75615034a2a98e)()const= &::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator > >::operator*;
::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::ConditionalDistributionEstimation< ::statiskit::MultivariateConditionalDistribution >::Estimator, ::std::default_delete< ::statiskit::ConditionalDistributionEstimation< ::statiskit::MultivariateConditionalDistribution >::Estimator > >::*method_pointer_ee61393c0e9f5844ae4a490f5568956f)()const= &::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator > >::get;
::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::ConditionalDistributionEstimation< ::statiskit::MultivariateConditionalDistribution >::Estimator, ::std::default_delete< ::statiskit::ConditionalDistributionEstimation< ::statiskit::MultivariateConditionalDistribution >::Estimator > >::*method_pointer_58fc7bd2d7bb54f49138ea689255740e)()= &::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator > >::release;
void  (::std::unique_ptr< ::statiskit::ConditionalDistributionEstimation< ::statiskit::MultivariateConditionalDistribution >::Estimator, ::std::default_delete< ::statiskit::ConditionalDistributionEstimation< ::statiskit::MultivariateConditionalDistribution >::Estimator > >::*method_pointer_2b4649d7fd425bc89c951b0ace68e1ad)(::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator > >::pointer )= &::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator > >::reset;
void  (::std::unique_ptr< ::statiskit::ConditionalDistributionEstimation< ::statiskit::MultivariateConditionalDistribution >::Estimator, ::std::default_delete< ::statiskit::ConditionalDistributionEstimation< ::statiskit::MultivariateConditionalDistribution >::Estimator > >::*method_pointer_225e1c93a5065f1a99cb69de15b80c66)(class ::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator > > &)= &::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator > >::swap;

namespace autowig {
    void method_decorator_7302531c823b59459c75615034a2a98e(class ::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator > > const & instance, const class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >::Estimator & param_out) { instance.operator*() = param_out; }
}

void wrapper_5180cb0278d15668832646c0905783b8(pybind11::module& module)
{

}