#include "_core.h"

class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution > & (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::MultivariateDistribution >, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::MultivariateDistribution > > >::*method_pointer_b7f720b5bb8f5605a6bed9106727dfd6)()const= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution > > >::operator*;
::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution > > >::pointer  (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::MultivariateDistribution >, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::MultivariateDistribution > > >::*method_pointer_bb5c7a946c815f90b3f68dae84d0b78c)()const= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution > > >::get;
::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution > > >::pointer  (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::MultivariateDistribution >, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::MultivariateDistribution > > >::*method_pointer_65ed0400d5e95b948764199bc264f4af)()= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution > > >::release;
void  (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::MultivariateDistribution >, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::MultivariateDistribution > > >::*method_pointer_a78edea1e19b545c9c32c1fcaca15f61)(::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution > > >::pointer )= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution > > >::reset;
void  (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::MultivariateDistribution >, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::MultivariateDistribution > > >::*method_pointer_ea69ae6aa4d95027b22a09c0ade8c924)(class ::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution > > > &)= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution > > >::swap;

namespace autowig {
    void method_decorator_b7f720b5bb8f5605a6bed9106727dfd6(class ::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution > > > const & instance, const class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution > & param_out) { instance.operator*() = param_out; }
}

void wrapper_34c2a8dbedd15f6e89c09855550f107b(pybind11::module& module)
{

}