#include "_core.h"

class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator & (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::SingularDistribution >::Estimator, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::SingularDistribution >::Estimator > >::*method_pointer_53d50b882dcd514bac8ba2f7964d87d0)()const= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator > >::operator*;
::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::SingularDistribution >::Estimator, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::SingularDistribution >::Estimator > >::*method_pointer_e8667edb2c9d5e778517f9cdcc0488aa)()const= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator > >::get;
::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::SingularDistribution >::Estimator, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::SingularDistribution >::Estimator > >::*method_pointer_cb0343b902ad5926a7e0e35142828ff7)()= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator > >::release;
void  (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::SingularDistribution >::Estimator, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::SingularDistribution >::Estimator > >::*method_pointer_7f6e13a466f75911b230284f278e6644)(::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator > >::pointer )= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator > >::reset;
void  (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::SingularDistribution >::Estimator, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::SingularDistribution >::Estimator > >::*method_pointer_b2b79f9ff31953dab19a3b963d5b455c)(class ::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator > > &)= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator > >::swap;

namespace autowig {
    void method_decorator_53d50b882dcd514bac8ba2f7964d87d0(class ::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator > > const & instance, const class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >::Estimator & param_out) { instance.operator*() = param_out; }
}

void wrapper_a0e97d92179d57c6b360e221cdb4303b(pybind11::module& module)
{

}