#include "_core.h"

class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator & (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::UnivariateDistribution >::Estimator, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::UnivariateDistribution >::Estimator > >::*method_pointer_ae7827e8006c5eeeb7edbe3b83c035b1)()const= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator > >::operator*;
::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::UnivariateDistribution >::Estimator, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::UnivariateDistribution >::Estimator > >::*method_pointer_fca116f8914c50dd978ea12973e9d27b)()const= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator > >::get;
::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::UnivariateDistribution >::Estimator, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::UnivariateDistribution >::Estimator > >::*method_pointer_f9e3364a79b85e5988821fc54e7859a9)()= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator > >::release;
void  (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::UnivariateDistribution >::Estimator, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::UnivariateDistribution >::Estimator > >::*method_pointer_5463b8114e9a5b20837f3c0babd2d4dc)(::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator > >::pointer )= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator > >::reset;
void  (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::UnivariateDistribution >::Estimator, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::UnivariateDistribution >::Estimator > >::*method_pointer_d5a72b6ea0ca5736a563850990f68b40)(class ::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator > > &)= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator > >::swap;

namespace autowig {
    void method_decorator_ae7827e8006c5eeeb7edbe3b83c035b1(class ::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator > > const & instance, const class ::statiskit::DistributionEstimation< struct ::statiskit::UnivariateDistribution >::Estimator & param_out) { instance.operator*() = param_out; }
}

void wrapper_621822ae142e56979bee170334c7a63a(pybind11::module& module)
{

}