#include "_core.h"

class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution > & (::std::unique_ptr< ::statiskit::ConditionalDistributionEstimation< ::statiskit::UnivariateConditionalDistribution >, ::std::default_delete< ::statiskit::ConditionalDistributionEstimation< ::statiskit::UnivariateConditionalDistribution > > >::*method_pointer_d345ff1e96a3554d8b9c4818e31dc05d)()const= &::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution >, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution > > >::operator*;
::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution >, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution > > >::pointer  (::std::unique_ptr< ::statiskit::ConditionalDistributionEstimation< ::statiskit::UnivariateConditionalDistribution >, ::std::default_delete< ::statiskit::ConditionalDistributionEstimation< ::statiskit::UnivariateConditionalDistribution > > >::*method_pointer_652a7449119f562daaa83ecefd03d497)()const= &::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution >, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution > > >::get;
::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution >, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution > > >::pointer  (::std::unique_ptr< ::statiskit::ConditionalDistributionEstimation< ::statiskit::UnivariateConditionalDistribution >, ::std::default_delete< ::statiskit::ConditionalDistributionEstimation< ::statiskit::UnivariateConditionalDistribution > > >::*method_pointer_c3eae19692d35f92bf29918bb1937e65)()= &::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution >, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution > > >::release;
void  (::std::unique_ptr< ::statiskit::ConditionalDistributionEstimation< ::statiskit::UnivariateConditionalDistribution >, ::std::default_delete< ::statiskit::ConditionalDistributionEstimation< ::statiskit::UnivariateConditionalDistribution > > >::*method_pointer_5af96673a6c050219d978bfa03895619)(::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution >, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution > > >::pointer )= &::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution >, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution > > >::reset;
void  (::std::unique_ptr< ::statiskit::ConditionalDistributionEstimation< ::statiskit::UnivariateConditionalDistribution >, ::std::default_delete< ::statiskit::ConditionalDistributionEstimation< ::statiskit::UnivariateConditionalDistribution > > >::*method_pointer_ef454c0ed4385c888397181e26407495)(class ::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution >, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution > > > &)= &::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution >, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution > > >::swap;

namespace autowig {
    void method_decorator_d345ff1e96a3554d8b9c4818e31dc05d(class ::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution >, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution > > > const & instance, const class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::UnivariateConditionalDistribution > & param_out) { instance.operator*() = param_out; }
}

void wrapper_294225563b8d53458805fdd4cfd054de(pybind11::module& module)
{

}