#include "_core.h"

class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution > & (::std::unique_ptr< ::statiskit::ConditionalDistributionEstimation< ::statiskit::MultivariateConditionalDistribution >, ::std::default_delete< ::statiskit::ConditionalDistributionEstimation< ::statiskit::MultivariateConditionalDistribution > > >::*method_pointer_955763c5802b5d1ab55552a6ae7304e5)()const= &::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution > > >::operator*;
::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution > > >::pointer  (::std::unique_ptr< ::statiskit::ConditionalDistributionEstimation< ::statiskit::MultivariateConditionalDistribution >, ::std::default_delete< ::statiskit::ConditionalDistributionEstimation< ::statiskit::MultivariateConditionalDistribution > > >::*method_pointer_d5c918acc57f550d85d4435d86e1cad7)()const= &::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution > > >::get;
::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution > > >::pointer  (::std::unique_ptr< ::statiskit::ConditionalDistributionEstimation< ::statiskit::MultivariateConditionalDistribution >, ::std::default_delete< ::statiskit::ConditionalDistributionEstimation< ::statiskit::MultivariateConditionalDistribution > > >::*method_pointer_7c4ba79fe94e543c9dc99eabbf0a43ed)()= &::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution > > >::release;
void  (::std::unique_ptr< ::statiskit::ConditionalDistributionEstimation< ::statiskit::MultivariateConditionalDistribution >, ::std::default_delete< ::statiskit::ConditionalDistributionEstimation< ::statiskit::MultivariateConditionalDistribution > > >::*method_pointer_bb7c5b23a58b509cacfc8a2127bc01dd)(::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution > > >::pointer )= &::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution > > >::reset;
void  (::std::unique_ptr< ::statiskit::ConditionalDistributionEstimation< ::statiskit::MultivariateConditionalDistribution >, ::std::default_delete< ::statiskit::ConditionalDistributionEstimation< ::statiskit::MultivariateConditionalDistribution > > >::*method_pointer_61a775dcdf135e3297c83242ecaf9145)(class ::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution > > > &)= &::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution > > >::swap;

namespace autowig {
    void method_decorator_955763c5802b5d1ab55552a6ae7304e5(class ::std::unique_ptr< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution >, struct ::std::default_delete< class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution > > > const & instance, const class ::statiskit::ConditionalDistributionEstimation< struct ::statiskit::MultivariateConditionalDistribution > & param_out) { instance.operator*() = param_out; }
}

void wrapper_a07113fabe3b5ca2bb7456220de98547(pybind11::module& module)
{

}