#include "_core.h"

class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution > & (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::SingularDistribution >, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::SingularDistribution > > >::*method_pointer_62bed2e74471562d97d64baa50d2c5a4)()const= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution > > >::operator*;
::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution > > >::pointer  (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::SingularDistribution >, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::SingularDistribution > > >::*method_pointer_21b775d7034d510596323374324eb8b7)()const= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution > > >::get;
::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution > > >::pointer  (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::SingularDistribution >, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::SingularDistribution > > >::*method_pointer_1fbb9503e1e35ad28669cdd0f06c5b5c)()= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution > > >::release;
void  (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::SingularDistribution >, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::SingularDistribution > > >::*method_pointer_02358e1ef4735543bc1ed61f4ceea3c3)(::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution > > >::pointer )= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution > > >::reset;
void  (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::SingularDistribution >, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::SingularDistribution > > >::*method_pointer_187dd6c0a7d65cdfa35d2525d232be31)(class ::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution > > > &)= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution > > >::swap;

namespace autowig {
    void method_decorator_62bed2e74471562d97d64baa50d2c5a4(class ::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution >, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution > > > const & instance, const class ::statiskit::DistributionEstimation< struct ::statiskit::SingularDistribution > & param_out) { instance.operator*() = param_out; }
}

void wrapper_a700d305386f53d0ae8398580f9913c3(pybind11::module& module)
{

}