#include "_core.h"

class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator & (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::MultivariateDistribution >::Estimator, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::MultivariateDistribution >::Estimator > >::*method_pointer_04dcff2be3905b3f9de4afcad2c82cda)()const= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator > >::operator*;
::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::MultivariateDistribution >::Estimator, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::MultivariateDistribution >::Estimator > >::*method_pointer_b90a92e7a79a59aebb37f0e1d3eb0274)()const= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator > >::get;
::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator > >::pointer  (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::MultivariateDistribution >::Estimator, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::MultivariateDistribution >::Estimator > >::*method_pointer_64cd49f0652c581a9bd817a188cfd783)()= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator > >::release;
void  (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::MultivariateDistribution >::Estimator, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::MultivariateDistribution >::Estimator > >::*method_pointer_4dc2e43a707d5a52a3e6d46567cb67b5)(::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator > >::pointer )= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator > >::reset;
void  (::std::unique_ptr< ::statiskit::DistributionEstimation< ::statiskit::MultivariateDistribution >::Estimator, ::std::default_delete< ::statiskit::DistributionEstimation< ::statiskit::MultivariateDistribution >::Estimator > >::*method_pointer_0d5124b4ba455173b3e3be0832badbdf)(class ::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator > > &)= &::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator > >::swap;

namespace autowig {
    void method_decorator_04dcff2be3905b3f9de4afcad2c82cda(class ::std::unique_ptr< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator, struct ::std::default_delete< class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator > > const & instance, const class ::statiskit::DistributionEstimation< struct ::statiskit::MultivariateDistribution >::Estimator & param_out) { instance.operator*() = param_out; }
}

void wrapper_c87812df9e2e5ead9306b7d4fbe06d71(pybind11::module& module)
{

}