package:
  name: libstatiskit_core-dev
  version: "1.0.0"

source:
  path: ../../..

build:
  number: 0
  detect_binary_files_with_prefix: False

about:
  home: http://statiskit-stl.readthedocs.org
  license: Apache License 2.0
  summary: C++ Development Files of Basic Utilities for Statistical Analyses

requirements:
  build:
    - python
    - libtoolchain
    - libtoolchain-dev
    - libstatiskit_stl-dev
    - libstatiskit_linalg-dev
    - libboost_core-dev
    # - gcc_impl_linux-64 7.2.0 hc5ce805_2
  run:
    - python
    - libstatiskit_stl-dev
    - libstatiskit_linalg-dev
    - libboost_core-dev