package:
  name: libstatiskit_core-dev
  version: "1.0.0"

source:
  path: ../../..

build:
  number: 0

about:
  home: http://statiskit-stl.readthedocs.org
  license: Apache License 2.0
  summary: C++ Development Files for Basic Utilities for Statistical Analyses

requirements:
  build:
    - python
    - libtoolchain
    - libtoolchain-dev
    - libstatiskit_stl-dev
    - libstatiskit_linalg-dev
  run:
    - python
    - libstatiskit_stl-dev
    - libstatiskit_linalg-dev