package:
  name: python-statiskit_core
  version: "1.0.0"

source:
  path: ../../..

build:
  number: 0

about:
  home: http://statiskit-core.readthedocs.io
  license: Apache License 2.0
  summary: A Python Interface from C++ Library of Basic Utilities for Statistical Analyses

requirements:
  build:
    - libtoolchain
    - python-toolchain
    - libboost_core-dev
    - libstatiskit_core-dev
    - libstatiskit_core
    - libboost_python-dev
    - libboost_python
    - python
  run:
    - libboost_python
    - libstatiskit_core
    - python-statiskit_linalg
    - python-statiskit_stl
    - python

test:                                               
  requires:
    - python-toolchain
    - matplotlib
    - numpy
  imports:
    - statiskit.core
  source_files:                                
    - test/test_*.py
  commands:                                       
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and linux" [linux]
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and osx"   [osx]
   - nosetests test -x -s -v -A "level <= {{ environ.get('TEST_LEVEL', 3) }} and win"   [win]
